version: "3.8"

services:
    mariadb:
        image: mariadb:latest
        container_name: bdmariadb1
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
